apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        app: myapp
        type: test
    spec:
      containers:
       - name: nginx
         image: nginx
  selector:
    matchLabels:
      app: myapp
