apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replication-controller
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        app: myapp
        type: test
    spec:
      containers:
       - name: nginx
         image: nginx
