apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica-set
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        app: myapp
        type: test
    spec:
      containers:
       - name: nginx
         image: nginx
  selector:
    matchLabels:
      app: myapp
